### ISSUE TITLE
 Could not find a valid package.json - feathers generate service

### ISSUE THREAD

**Issue by Shadowman4205** [feathersjs/feathers-cli#102]
>  Could not find a valid package.json. Did you generate a new application and are running the generator in the project directory?

With previous version i could do feathers generate but now it ask for package.json. I want to generate only the service.

Is this how it works now? or i can do something?

**Comment by daffl** [comment]
You have to generate an application (`feathers generate app`) first and make sure that you run the service generator in the root level of your project.

**Comment by Shadowman4205** [comment]
Ok thanks. I needed only the service generator.
