### ISSUE TITLE
No model file when creating service (bug or feature?)

### ISSUE THREAD

**Issue by mpkelly** [feathersjs/feathers-cli#103]
Hello, 

I am using a brand new installation of package feathers-cli@.2.2.3 When creating a new service with this package I do not see a model file. Is this expected for this version? (I have not used feathers for about six months but it previously output a model file.) According to the docs, the model file should still be present. 

Here's the output: 

```
Michaels-MacBook-Air:feathersjs Mike$ feathers generate service
? What kind of service is it? MongoDB
? What is the name of the service? myservice
? Which path should the service be registered on? /myservice
? What is the database connection string? mongodb://localhost:27017/feathersjs
    force config/default.json
   create src/services/myservice/myservice.service.js
    force src/services/index.js
   create src/services/myservice/myservice.hooks.js
   create src/services/myservice/myservice.filters.js
   create test/services/myservice.test.js
   create src/mongodb.js
    force src/app.js
npm WARN feathersjs@0.0.0 No repository field.
npm WARN feathersjs@0.0.0 No license field.

+ feathers-mongodb@2.9.0
added 3 packages in 5.573s
npm WARN feathersjs@0.0.0 No repository field.
npm WARN feathersjs@0.0.0 No license field.

+ mongodb@2.2.30
added 10 packages in 8.625s
```

Also, what is the different between the Yeoman and Metalsmith generators? The feathers-cli appears to be using the Yeoman generator. However, I noticed that the[ Metalsmith package](https://github.com/feathersjs/feathers-generator) has a "model" generator. Should I be using this instead?

**Comment by mpkelly** [comment]
FYI I am currently working with v2.1.0 which outputs a model file.

**Comment by mpkelly** [comment]
Hmm. I was incorrectly selecting "Mongo" and not "Mongoose"! You don't get a model file unless you select the framework. 

Closing.

**Comment by daffl** [comment]
Yep, standard MongoDB does not have a model. You can see for which adapters models are generated at https://github.com/feathersjs/generator-feathers/tree/master/generators/service/templates/model

**Comment by mpkelly** [comment]
Thanks for the additional info.

**Comment by crobinson42** [comment]
@daffl I'm not getting a `[service name].model.js` file when using Mongoose, am I missing something?

```
$ feathers --version
2.3.5
```

![screenshot 2017-09-01 09 42 56](https://user-images.githubusercontent.com/5973579/29979349-f31243cc-8ef9-11e7-90a4-a98d2f3298ae.png)

**Comment by daffl** [comment]
@crobinson42 If you look at the file list you can see that it created a `src/models/accounts.model.js`. Models live at the top level folder because they may be shared between different services.

**Comment by crobinson42** [comment]
Ouch. :headbang:
