### ISSUE TITLE
Remove the "generate" command shortcut

### ISSUE THREAD

**Issue by derek-watson** [feathersjs/feathers-cli#14]
Remove the `generate` command, which is currently a shortcut for `generate app`. This allows us to accept set application name and directory to create as `generate app [app name]`.

**Comment by ekryski** [comment]
This is cleaned up in the 2.0 branch. You can now run:

- `feathers generate [g] app <app-name>` - without a name it will attempt to use the current directory as the name and prompt for confirmation.
