### ISSUE TITLE
Generate Hooks

### ISSUE THREAD

**Issue by sscaff1** [feathersjs/feathers-cli#18]
I'm having a problem where I can't generate a hook if I specify where the hook should be used. Here is the code I'm running in my feather app root directory. This is straight from the docs
```
feathers generate hook
? What do you want to call your hook? gravatar
? What type of hook do you need? before hook
? What service is this hook for? user
? What method is this hook for? create
```
No file was created in this instance above. If I don't specify what method(s) the hook is for, then it generates the hook.
```
feathers generate hook
? What do you want to call your hook? gravatar
? What type of hook do you need? before hook
? What service is this hook for? user
? What method is this hook for? 
   create src/services/user/hooks/gravatar.js
   create test/services/user/hooks/gravatar.test.js
```
I just ran `npm i -g feathers-cli` so I'm running the latest version. Any ideas?

**Comment by ekryski** [comment]
Hmm going to look into it @sscaff1. There are some issues with the CLI calling yeoman under the hood. Worst case you can try just using `yo feathers:hook`.

**Comment by sscaff1** [comment]
Thanks @ekryski! Not a big deal either way - just wanted to bring this to your attention.

**Comment by daffl** [comment]
I'm wondering if this is fixed through https://github.com/feathersjs/generator-feathers/pull/111 (which was originally reported in https://github.com/feathersjs/feathers/issues/295 where you couldn't choose methods in certain cases). Can you try again with the latest version?

**Comment by lnguyenfx** [comment]
I've updated to the latest version of `feathers-cli` and was able to generate new hooks for the User service. Hope this help.

**Comment by daffl** [comment]
Thank you. I'm going to close this then because it seems to be solved with the generator update.
