### ISSUE TITLE
Using a hyphen in service name silently fails.

### ISSUE THREAD

**Issue by toddgeist** [feathersjs/feathers-cli#19]
When generating a new service with the cli, there is no error if you name the service with a hyphen.  For example: calling your service `test-service` will silently fail.

Start with a new app then use the cli to do the following.

```
$ feathers generate service

? What do you want to call your service? test-service
? What type of service do you need? generic
? Does your service require users to be authenticated? Yes
$
```

There is no error and the service is not created.

**Comment by daffl** [comment]
Thank you. That is indeed true. Instead of an error (or just failing) we will try to insert a valid variable name.  I created a follow-up issue https://github.com/feathersjs/generator-feathers/issues/113 in the generator.

@derek-watson Could the CLI be swallowing errors here?

**Comment by beebase** [comment]
It seems that events ('created', 'removed' etc..) are not arriving from client to server, or at least I'm not seeing any traces/logs. I think it's related to the naming of a service. I tried this with several services and after re-creating a service with different naming everything worked.

"bookmark-skill" remains silent
   
```
? What kind of service is it? A custom service
? What is the name of the service? bookmark-skill
? Which path should the service be registered on? /bookmark-skill
? Does the service require authentication? No
   create src/services/bookmark-skill/bookmark-skill.service.js
    force src/services/index.js
   create src/services/bookmark-skill/bookmark-skill.class.js
   create src/services/bookmark-skill/bookmark-skill.hooks.js
   create src/services/bookmark-skill/bookmark-skill.filters.js
   create test/services/bookmark-skill.test.js
```
"bookmarkskill" works ok
```
? What kind of service is it? A custom service
? What is the name of the service? bookmarkskill
? Which path should the service be registered on? /bookmarkskill
? Does the service require authentication? No
   create src/services/bookmarkskill/bookmarkskill.service.js
    force src/services/index.js
   create src/services/bookmarkskill/bookmarkskill.class.js
   create src/services/bookmarkskill/bookmarkskill.hooks.js
   create src/services/bookmarkskill/bookmarkskill.filters.js
   create test/services/bookmarkskill.test.js
```
