### ISSUE TITLE
Add rethinkdb support

### ISSUE THREAD

**Issue by iovative** [feathersjs/feathers-cli#23]
Hey guys, great work on everything so far.  Now that the official feathers-rethinkdb adapter is out, I would like to get the support added to the new project creation and service generator.  Thanks!

ceero

**Comment by briandpassa** [comment]
Hi, is the rethinkdb support enabled?

**Comment by daffl** [comment]
No. You will have to create your own generator or do it manually as [described in the documentation](http://docs.feathersjs.com/databases/rethinkdb.html). Any help to get it into this generator would also be much appreciated.
