### ISSUE TITLE
Add command to list existing services

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-cli#30]
As described in https://github.com/feathersjs/generator-feathers/issues/139.

**Comment by alnour-altegani** [comment]
any progress about this feature ?

**Comment by daffl** [comment]
This is outside of the scope for the generator. The next version will list available service (based on folder names) when generating a new hook and model.

**Comment by alnour-altegani** [comment]
it is not in the scope of the generator but the feathers cli tool . in laravel if I run
```bash
php artisan route:list
```
I will get all the routes paths . with middlewares(hooks like) and controller (service like) .
it is possible to enhance this cli tool to do more than generating like (give Bird's-eye view, inspect or interact with the application services ...'  . 
is there any additional enhancements in the v 2.0 for this command line tool ?

**Comment by daffl** [comment]
A CLI tool is a lot of work to maintain. With our limited resources we have to cut down the scope of what it does. Of course this shouldn't keep anybody from contributing that functionality.

There might be a tool that can handle all those things in the near future but it won't be open source or free.

**Comment by alnour-altegani** [comment]
Thanks for the clarification
