### ISSUE TITLE
Add service to manage file uploads

### ISSUE THREAD

**Issue by silvestreh** [feathersjs/feathers-cli#36]
It would be awesome to be able to generate a service to manage file uploads. Maybe even ask wether the user wants to use S3 or just upload to a directory inside `public/`. 

If the user selects S3, maybe prompt for AWS Key and Secret and then add that to the config file?

**Comment by daffl** [comment]
We have a great guide [here](https://docs.feathersjs.com/guides/file-uploading.html). For now this is probably outside of the scope of the generator but we'll be happy to take it as a contribution.
