### ISSUE TITLE
Update dependencies: feathers-configuration

### ISSUE THREAD

**Issue by kulakowka** [feathersjs/feathers-cli#37]
Could we update dependencies in the generator?

```
Package                 Current  Wanted  Latest  
feathers-configuration    0.2.3   0.2.3   0.3.1 
```

I tried to do it locally. Nothing is broken. The tests were successful.

**Comment by daffl** [comment]
Apparently I already did that in https://github.com/feathersjs/generator-feathers/commit/57cce4979fd067c5d325478d912f65abf2092378 but never release it. Should be fixed now in generator-feathers 0.8.8
