### ISSUE TITLE
[2.0] Ability to generate/rotate secrets

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-cli#46]
Something like `feathers generate secret` which at the very least spits out a new secure secret to copy to your `.json` config files or `.env` or something.

Depending on how we want to handle secret rotation and what shakes out of https://github.com/feathersjs/feathers-configuration/issues/24 we might be able to auto-rotate.

**Comment by marshallswain** [comment]
related to https://github.com/feathersjs/feathers-authentication/issues/309

**Comment by daffl** [comment]
Added in the latest generator (feathers-cli@2.0.0-pre), see https://github.com/feathersjs/generator-feathers/pull/163
