### ISSUE TITLE
Support yarn for generating app

### ISSUE THREAD

**Issue by lednhatkhanh** [feathersjs/feathers-cli#53]
Since yarn is way more faster than npm so I think it's a great time to start supporting yarn when generating new feathers app.

I think it's a good idea to detect yarn is installed on the current system and provide an option to use yarn instead of npm when running `feathers generate`

**Comment by marshallswain** [comment]
We are all fans of Yarn.  Sounds like a plan to me.  Just have to work it into the priorities.

**Comment by daffl** [comment]
Currently it's using Yeomans `npm` dependency management. I'm not sure they added alternate package manager support yet.

**Comment by marshallswain** [comment]
Yarn support just landed a few days ago.

**Comment by daffl** [comment]
This has been added to the https://github.com/feathersjs/generator-feathers/tree/generator-refactoring branch and will be available in the next version.

**Comment by OmgImAlexis** [comment]
@daffl I'm using the latest version of feathers-cli and it looks like npm is still being used to install the project as well as there's no `yarn.lock` being generated. 

Any ideas?

**Comment by daffl** [comment]
With `npm install feathers-cli@pre -g` (and confirming that `npm ls generator-feathers -g` shows `v1.0.0-pre.5` or later) definitely asks for the package manager:

<img width="578" alt="screen shot 2017-03-04 at 8 12 46 pm" src="https://cloud.githubusercontent.com/assets/338316/23584453/f6da874c-0116-11e7-8d46-
7c4d83089478.png">
