### ISSUE TITLE
support new feathers-authentication 1.0 and feathers-configuration 0.4?

### ISSUE THREAD

**Issue by beeplin** [feathersjs/feathers-cli#54]
Both the two packages have considerable breaking changes.

**Comment by wallaceicy06** [comment]
+1

**Comment by jfcieslak** [comment]
The new feathers-authentication (1.0+) works great and seems to solve some annoying problems that the older versions had. I am using 1.0 in new projects, however now I have to manually fix the config every time I scaffold app or services with the cli, so yeah, an upgrade for the cli supporting new packages would be sooo cool!

**Comment by marshallswain** [comment]
Thanks, y'all.  This is in active development.

**Comment by IBwWG** [comment]
It's very confusing to a newcomer reading through the docs, which guide you to use the scaffolding, then have your app complain with things like

```
info: MethodNotAllowed: The 'hasRoleOrRestrict' hook should only be used on the
'get', 'update', 'patch' and 'remove' service methods if you are using the 'owner' field.
```
...when the docs say explicitly that it's for 'get' and 'fetch'.

Then you go into the old code and start finding things that don't make sense...before realizing that you're not on the version that matches the docs that told you to use the cli that installed it for you.  :)

So...+1 :)

**Comment by IBwWG** [comment]
Although even more confusingly, the docs for 'latest stable' don't match what's in 1.0.2 either, which moved things like restrictToRoles into feathers-permissions.

**Comment by IBwWG** [comment]
Which is not published yet...

**Comment by daffl** [comment]
Neither the docs nor the generator are pointing to auth 1.0. I just installed the CLI and generated a working app with the old auth setup without issues.

**Comment by IBwWG** [comment]
Then I'm not sure what the docs are talking about, but they're not in sync with what the CLI installs.

https://docs.feathersjs.com/authorization/bundled-hooks.html#hasroleorrestrict says, "hasRoleOrRestrict is meant to be used as a before hook for any service on the find or get methods."

Use the CLI installer, then try using that on a `find` hook and you get the error I mentioned above in https://github.com/feathersjs/feathers-cli/issues/54#issuecomment-271089410

**Comment by eddyystop** [comment]
The repo is scheduled for a rewrite when authentication and permissions
have settled down.

Also, several things have been pulled from this repo into feathers-core,
and undergone some significant changes. The rewrite has to reflect that too.

I consider the issues you've posted valuable and they'll be addressed pre
and post rewrite.

**Comment by IBwWG** [comment]
Thanks, but...wouldn't it be good (since auth/perms originally had a 'by november' msg on it and everyone is busy right now) to put a notice in the docs that they're in flux, to prevent n00bs from going down the rabbit hole too far?  I can PR one if that's an amenable stopgap :)
