### ISSUE TITLE
Services become plural?

### ISSUE THREAD

**Issue by tvld** [feathersjs/feathers-cli#55]
Being new ..today... with Feathers, following the Quick start, I ran ``feathers generate service`` and entered my service name ``transponder``.

I expect to be able to call ``http://localhost:3030/transponder`` but the call that works is ``http://localhost:3030/transponders`` (note the plural 's')

Bug? My misunderstanding? Are service names to be required in English only?

**Comment by eddyystop** [comment]
I believe the generator pluralizes always, user item -> users. service

**Comment by tvld** [comment]
It seems so. but a bit weird especially if we don't use English ;)

Anyway... seems like a 'feature' and not a 'bug' so I will close... and re-edit all by hand ;)
