### ISSUE TITLE
Generate and run database migrations

### ISSUE THREAD

**Issue by derek-watson** [feathersjs/feathers-cli#6]

**Comment by daffl** [comment]
I'm going to close this. I think for now migrations are dependent on the ORM and can be documented by a guide like [in the Sequelize documentation](http://docs.feathersjs.com/databases/sequelize.html). We might circle back to this when developing a general one-model solution for Feathers.

**Comment by zedaan** [comment]
I just created new service with model definitions, doesn't it creates db table by itself? When I added authentication to the table, it created table for me. I was expecting same behavior.
