### ISSUE TITLE
Add support for version argument

### ISSUE THREAD

**Issue by OmgImAlexis** [feathersjs/feathers-cli#66]
Right now feathers-cli can't be passed `-v` or `--version` to get the version for debugging.

**Comment by daffl** [comment]
Try installing the next version with `npm install feathers-cli@pre -g`. It does have a `-V` flag.

**Comment by OmgImAlexis** [comment]
That solves this and the yarn issue I tagged you in. Without being able to see the version there wasn't any way of me knowing latest wasn't pointing to pre.

**Comment by OmgImAlexis** [comment]
Also wouldn't it make more sense to use `-v` as help's alias is `-h` not `-H`?
