### ISSUE TITLE
Generate stand alone micro-services not hard-linked to app/route

### ISSUE THREAD

**Issue by kristianmandrup** [feathersjs/feathers-cli#68]
Would love to see the generator have an option to spit out a service in `Object` or `class` format that is not hard-linked to the app but can be used stand-alone, composed with other services etc.
Should respect some kind of project config parameters, such as convention being used (class vs Object, promise vs callback etc.)

Generator should be more customisable as outlined/requested in #38

Currently way too hardcoded to be hooked on directly to the route. Does it only support Express?!

```
'use strict';

const path = require('path');
const NeDB = require('nedb');
const service = require('feathers-nedb');
const hooks = require('./hooks');

module.exports = function(){
  const app = this;

  const db = new NeDB({
    filename: path.join(app.get('nedb'), 'users.db'),
    autoload: true
  });

  let options = {
    Model: db,
    paginate: {
      default: 5,
      max: 25
    }
  };

  // Initialize our service with any options it requires
  app.use('/users', service(options));

  // Get our initialize service to that we can bind hooks
  const userService = app.service('/users');

  // Set up our before hooks
  userService.before(hooks.before);

  // Set up our after hooks
  userService.after(hooks.after);
};
```

Should be more something like this IMO. How can we customize the templates being used?

```
module.exports = {
  find(params [, callback]) {},
  get(id, params [, callback]) {},
  create(data, params [, callback]) {},
  update(id, data, params [, callback]) {},
  patch(id, data, params [, callback]) {},
  remove(id, params [, callback]) {},
  setup(app, path) {}
}
```

**Comment by daffl** [comment]
Customization is best done by forking the [generator-feathers](https://github.com/feathersjs/generator-feathers/) repository and modifying it to your needs.

Unfortunately, in order to attach hooks we need to have access to the [wrapped service object](https://docs.feathersjs.com/api/readme.html#service) and in order to get the options we need the `app` object.

You could do something like

```js
'use strict';

const path = require('path');
const NeDB = require('nedb');
const { Service } = require('feathers-nedb');
const hooks = require('./hooks');

class CustomService extends Service {
  setup() {
    this.hooks(hooks);
  }  
}

module.exports = function(app) {
  const db = new NeDB({
    filename: path.join(app.get('nedb'), 'users.db'),
    autoload: true
  });

  let options = {
    Model: db,
    paginate: {
      default: 5,
      max: 25
    }
  };

  return new CustomService(options);
};
```

and then use it like `app.use('/custom', customService(app))`. The drawback is that you have to call `app.setup` (or `app.listen`) in order for hooks for work.

**Comment by kristianmandrup** [comment]
Great :) Much more flexible aproach

**Comment by daffl** [comment]
I'm going to close this. As mentioned, if you would like to use this pattern you can fork the generator and use your fork but I would like to avoid changing the application structure that soon again.
