### ISSUE TITLE
Trailing whitespace in a few files

### ISSUE THREAD

**Issue by bitsoflogic** [feathersjs/feathers-cli#69]
Using `feathers generate`, then following the prompts (all default options), I noticed a few files with trailing whitespace in the generated project.  Happy to do a PR later.

Files affected:
/src/hooks/index.js
/src/middleware/logger.js
/src/services/authentication/index.js
/src/services/index.js

Also, running `generate model`, you get one in the comments there too.

**Comment by daffl** [comment]
Please try running the new generator (`npm install feathers-cli@pre -g`) to see if this is still an issue.

**Comment by bitsoflogic** [comment]
It all looks good.  Well played.
