### ISSUE TITLE
The CLI is using a feathers-authentication version < v0.8.0,  which is causing issues with mongodb + oatuh0

### ISSUE THREAD

**Issue by DaviTeodoro** [feathersjs/feathers-cli#72]
This issue -> https://github.com/feathersjs/feathers-authentication/issues/244 was solved on version 1.0.0 but today the CLI is using version 0.7.12 by default. 
If you, for exemple, create a app using the CLI + mongodb + oauth0 (I tested google) the loging will not work.

**Comment by daffl** [comment]
`npm install feathers-cli@pre -g` is using version 1.x. It will be the standard default once the docs are updated.
