### ISSUE TITLE
feathers not recognized as an internal or external command

### ISSUE THREAD

**Issue by GWSB** [feathersjs/feathers-cli#74]
### Steps to reproduce

From command prompt:

```
npm install -g feathers-cli

feathers --version
```

### Expected behavior

Expected feathers to be a command.

### Actual behavior
Tell us what happens instead

### System configuration
console returns

`'feathers' is not recognized as an internal or external command,
operable program or batch file.`

Tell us about the applicable parts of your setup.

**Module versions** whatever the npm command pulls

**NodeJS version**: 7.7.4

**Operating System**: Windows 10

**Module Loader**: Nodist

 I've verified that my path is set up correctly. Restarted my machine. Cleaned my npm cache. Only thing I can see that may be an issue is that I'm using Nodist instead of NVM. 

**EDIT: 
apparently it was the nodist install that was causing problems. Removing it from my system solved the issues.

**Comment by TeddyPerkins** [comment]
reinstall node v>11
