### ISSUE TITLE
automatically migrate from prev versions to 2.0

### ISSUE THREAD

**Issue by santomegonzalo** [feathersjs/feathers-cli#75]
Hi, first, I love feathersJS... It's awesome... 

I started a month a go with feathers-cli 1.x and then I migrated part of the app to use the latest authentication and it was a big mess... so I found the pre release of the cli have a new command to add authentication so I decided to update and then i found i cant run any command from feathers-cli because the app was generated with an old version. So that means I need to start from the beginning and be careful on what to do... is there any other way to use the **prerelease** with and old version of feathers and just update the project? or at least some steps to run manually to use the latest feathers-cli.

Thanks!

**Comment by marshallswain** [comment]
Hi, @santomegonzalo.  The scope of the generator is to help get an application started.  It is far too complicated to reliably handle the code transformations after the user has made even small changes.  And that's without even considering a second generator.  Short of copying code from the old app to the new, I'd recommend looking at the code the generator builds and copy the working auth code into your old application.

What made setting up the new auth a mess?
