### ISSUE TITLE
Generated sequelize service does not use the username and password correctly

### ISSUE THREAD

**Issue by jdhines** [feathersjs/feathers-cli#84]
### Steps to reproduce

1. `feathers generate service`
2. Pick Sequelize, Y for requires authentication, and SQL Server for the database
3. Entered a connection string with username and password like  `mssql://myusername:mypassword@server:1433/database`
4. Once service is created, in mssql.js, after line 7 (`const connection = url.parse(connectionString);`), put `console.log(connection);`
5. Run `npm start` and check the console

### Expected behavior
The console should show a `Url` object with properties `username` and `password`.

### Actual behavior
The console shows a `Url` object with an `auth` property that contains a string of the username and password like `myusername:mypassword`, but no properties `username` or `password`.

### System configuration
**Module versions** (especially the part that's not working):
feathers-cli v2.0.4
**NodeJS version**:
yarn v.0.22.0
npm v4.2.0
**Operating System**:
Mac OS X El Capitan
**Browser Version**:

**Module Loader**:
whatever comes with `feathers generate app`

**Comment by kadambs** [comment]
thank you
