### ISSUE TITLE
File postgres.js is overwritten when generating new service

### ISSUE THREAD

**Issue by chuan137** [feathersjs/feathers-cli#87]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [x] Tell us what broke. The more detailed the better.
I use sequelize/postgresql combination as service backend. Each time I generate a new service using command line (with an existing service using postgresql),
  ```
  feathers -g service
  ```
  the file postgres.js at root is overwritten.

- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

### Expected behavior
If the postgres.js has been generated, it should be skipped.

### Actual behavior
Instead the file is forced.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:
v7.9.0

**Operating System**:
Linux

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment]
Thank you! I fixed this last night in https://github.com/feathersjs/generator-feathers/pull/211 and released it in feathers-cli v2.0.5 (updated with `npm update feathers-cli -g`).
